language: python
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
  postgresql: 9.5
python:
  #- "2.7"
  - "3.4"
env:
  global:
   - PGPORT=5433
   - DATABASE_URL=postgresql://travis@:5433/pg-discuss
   - SECRET_KEY=not_a_secret
   - SERVER_NAME=localhost
   - PG_DISCUSS_SETTINGS_FILE=''
install:
  - python setup.py develop_tests
  - python blessed_extensions/setup.py develop
# command to run tests
before_script:
  - env
  - psql -c 'show server_version;'
  - psql -c 'create database "pg-discuss";'
  - psql $DATABASE_URL -c 'show server_version;'
  - python main.py db upgrade -d migrations
  - python main.py db upgrade -d ext_migrations
script: py.test tests
