"""empty message

Revision ID: 1ccadb332442
Revises: None
Create Date: 2015-09-05 06:52:53.451124

"""

# revision identifiers, used by Alembic.
revision = '1ccadb332442'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('custom_json', postgresql.JSONB(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('custom_json', postgresql.JSONB(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('version_of_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('modified', sa.DateTime(timezone=True), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('custom_json', postgresql.JSONB(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['version_of_id'], ['comment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_to_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('rel_type', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('custom_json', postgresql.JSONB(), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_to_comment')
    op.drop_table('comment')
    op.drop_table('thread')
    op.drop_table('identity')
    ### end Alembic commands ###
