"""empty message

Revision ID: 30cd6ea45e20
Revises: None
Create Date: 2015-08-19 01:33:40.892644

"""

# revision identifiers, used by Alembic.
revision = '30cd6ea45e20'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text(u'FALSE'), nullable=False),
    sa.Column('archived_from', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('modified', sa.DateTime(), server_default=sa.text(u'NOW()'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('custom_json', postgresql.JSONB(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    op.drop_table('comment')
    ### end Alembic commands ###
